name: Daily YouTube KPI (no Sheets)

on:
  schedule:
    - cron: "0 2 * * *"   # 02:00 UTC ≈ 07:30 IST
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  run-daily:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: daily-youtube-kpi
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write tokens (robust)
        shell: bash
        run: |
          set -euo pipefail
          if [[ -n "${{ secrets.YT_TOKENS_JSON_B64 || '' }}" ]]; then
            echo "${{ secrets.YT_TOKENS_JSON_B64 }}" | base64 --decode > yt_refresh_tokens.json
          elif [[ -n "${{ secrets.YT_TOKENS_JSON || '' }}" ]]; then
            printf '%s' "${{ secrets.YT_TOKENS_JSON }}" > yt_refresh_tokens.json
          else
            echo "❌ Provide YT_TOKENS_JSON_B64 (preferred) or YT_TOKENS_JSON"; exit 1
          fi
          chmod 600 yt_refresh_tokens.json

          # Validate JSON fast
          python - <<'PY'
          import json, pathlib
          json.loads(pathlib.Path("yt_refresh_tokens.json").read_text(encoding="utf-8"))
          print("✅ yt_refresh_tokens.json is valid JSON")
          PY

      - name: Run script
        env:
          # YouTube OAuth
          YT_CLIENT_ID:     ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}

          # Slack
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

          # Sheets disabled
          GOOGLE_SHEET_URL: ""
          SHEETS_AUTH_MODE: "service_account"
          SERVICE_ACCOUNT_JSON: "service_account.json"

          # Script config
          YT_TOKENS_FILE: yt_refresh_tokens.json
          YT_CURRENCY:    ${{ secrets.YT_CURRENCY || 'USD' }}
        run: python main.py
