name: YouTube KPIs → Slack (Revenue & Views)

on:
  schedule:
    # 07:30 IST daily = 02:00 UTC
    - cron: '0 1 * * *'
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: youtube-kpis
  cancel-in-progress: false

jobs:
  run-kpis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Use your repo requirements (keeps old deps) + add ours if missing
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install requests pandas gspread gspread-dataframe google-auth-oauthlib

      - name: Write auth files from secrets
        run: |
          echo '${{ secrets.YT_TOKENS_JSON }}' > yt_refresh_tokens.json
          if [ -n "${{ secrets.SERVICE_ACCOUNT_JSON }}" ]; then
            echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json
          fi
          # normalize line endings just in case
          sed -i 's/\r$//' yt_refresh_tokens.json || true
          test -f service_account.json && sed -i 's/\r$//' service_account.json || true

      # ---------- Revenue ----------
      - name: Post Revenue KPIs
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_TOKENS_FILE: yt_refresh_tokens.json
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_REVENUE }}
          GOOGLE_SHEET_URL: ${{ secrets.GOOGLE_SHEET_URL }}
          SERVICE_ACCOUNT_JSON: service_account.json
          SHEETS_AUTH_MODE: service_account
          SHEET_TAB: facts_revenue
          YT_CURRENCY: USD
        run: python adsense_kpi_poster.py

      # ---------- Views ----------
      - name: Post Views KPIs
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_TOKENS_FILE: yt_refresh_tokens.json
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_VIEWS }}
          GOOGLE_SHEET_URL: ${{ secrets.GOOGLE_SHEET_URL }}
          SERVICE_ACCOUNT_JSON: service_account.json
          SHEETS_AUTH_MODE: service_account
          SHEET_TAB: facts_views
        run: python views_kpi_poster.py
